[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  publish = ".next/standalone"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
