"use client";

import { useState } from "react";
import {
  BarChart3,
  FileText,
  Download,
  Calendar,
  TrendingUp,
  Users,
  MessageSquare,
  ClipboardCheck,
  Loader2,
  FileSpreadsheet,
  Eye,
  Mail,
  Clock,
  CheckCircle2,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { toast } from "@/hooks/use-toast";

const reportTypes = [
  {
    id: "daily",
    title: "Daily Report",
    description: "Daily operations summary including attendance, tasks, and complaints",
    icon: Calendar,
    frequency: "Daily",
  },
  {
    id: "weekly",
    title: "Weekly Report",
    description: "Weekly performance metrics and trend analysis",
    icon: TrendingUp,
    frequency: "Weekly",
  },
  {
    id: "mfr",
    title: "Monthly Facility Report (MFR)",
    description: "Comprehensive monthly report with all KPIs and metrics",
    icon: FileText,
    frequency: "Monthly",
  },
  {
    id: "quarterly",
    title: "Quarterly Report",
    description: "Quarterly business review with trends and recommendations",
    icon: BarChart3,
    frequency: "Quarterly",
  },
  {
    id: "attendance",
    title: "Attendance Report",
    description: "Employee attendance summary and statistics",
    icon: Users,
    frequency: "Custom",
  },
  {
    id: "complaints",
    title: "Complaint Analysis",
    description: "Complaint trends, SLA performance, and category breakdown",
    icon: MessageSquare,
    frequency: "Custom",
  },
  {
    id: "inspection",
    title: "Inspection Report",
    description: "Inspection scores and area-wise performance",
    icon: ClipboardCheck,
    frequency: "Custom",
  },
];

const reportHistory = [
  { id: "1", name: "MFR - December 2023", date: "Jan 1, 2024", type: "PDF", size: "2.4 MB", status: "ready" },
  { id: "2", name: "Weekly Report - Week 52", date: "Dec 31, 2023", type: "Excel", size: "1.8 MB", status: "ready" },
  { id: "3", name: "Attendance Report - December", date: "Dec 30, 2023", type: "PDF", size: "856 KB", status: "ready" },
  { id: "4", name: "Complaint Analysis - Q4 2023", date: "Dec 28, 2023", type: "PDF", size: "1.2 MB", status: "ready" },
  { id: "5", name: "Daily Report - Dec 27", date: "Dec 27, 2023", type: "PDF", size: "456 KB", status: "ready" },
];

const scheduledReports = [
  { id: "1", name: "Daily Operations Report", schedule: "Daily at 8:00 AM", recipients: "facility.manager@demo.com", enabled: true },
  { id: "2", name: "Weekly Summary Report", schedule: "Every Monday at 9:00 AM", recipients: "management@demo.com", enabled: true },
  { id: "3", name: "Monthly Facility Report", schedule: "1st of every month", recipients: "client@demo.com", enabled: true },
  { id: "4", name: "Attendance Report", schedule: "Every Friday at 6:00 PM", recipients: "hr@demo.com", enabled: false },
];

export default function ReportsPage() {
  const [selectedPeriod, setSelectedPeriod] = useState("this-month");
  const [generatingReport, setGeneratingReport] = useState<string | null>(null);
  const [previewDialog, setPreviewDialog] = useState<{ open: boolean; report: typeof reportTypes[0] | null }>({ open: false, report: null });
  const [scheduleList, setScheduleList] = useState(scheduledReports);

  const generatePDF = async (reportId: string, reportTitle: string) => {
    setGeneratingReport(`${reportId}-pdf`);

    // Simulate PDF generation
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Create sample PDF content
    const pdfContent = `
      SOFT SERVICES ERP - ${reportTitle}
      Generated on: ${new Date().toLocaleDateString()}
      Period: ${selectedPeriod.replace("-", " ").toUpperCase()}

      ========================================
      SUMMARY
      ========================================
      Total Tasks Completed: 156
      Attendance Rate: 94.5%
      Inspection Score: 87%
      Complaints Resolved: 23/25
      SLA Compliance: 92%

      ========================================
      This is a demo report generated by
      Soft Services ERP System
      ========================================
    `;

    const blob = new Blob([pdfContent], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${reportTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setGeneratingReport(null);
    toast({
      title: "PDF Generated",
      description: `${reportTitle} has been downloaded`,
    });
  };

  const generateExcel = async (reportId: string, reportTitle: string) => {
    setGeneratingReport(`${reportId}-excel`);

    // Simulate Excel generation
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Create CSV content (Excel compatible)
    const csvContent = `Report Title,${reportTitle}
Generated On,${new Date().toLocaleDateString()}
Period,${selectedPeriod.replace("-", " ").toUpperCase()}

Metric,Value,Target,Status
Tasks Completed,156,150,Above Target
Attendance Rate,94.5%,95%,Below Target
Inspection Score,87%,85%,Above Target
Complaints Resolved,23,25,In Progress
SLA Compliance,92%,90%,Above Target

Category,Count,Percentage
Housekeeping,45,29%
Technical,32,21%
Security,28,18%
Front Desk,25,16%
Others,26,16%
`;

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${reportTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setGeneratingReport(null);
    toast({
      title: "Excel Generated",
      description: `${reportTitle} has been downloaded as CSV`,
    });
  };

  const previewReport = (report: typeof reportTypes[0]) => {
    setPreviewDialog({ open: true, report });
  };

  const downloadHistoryReport = (report: typeof reportHistory[0]) => {
    toast({
      title: "Downloading...",
      description: `${report.name} is being downloaded`,
    });

    // Simulate download
    setTimeout(() => {
      const content = `Demo content for ${report.name}`;
      const blob = new Blob([content], { type: report.type === 'PDF' ? 'application/pdf' : 'text/csv' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${report.name.replace(/\s+/g, '_')}.${report.type.toLowerCase()}`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Download Complete",
        description: `${report.name} has been downloaded`,
      });
    }, 1000);
  };

  const toggleSchedule = (id: string) => {
    setScheduleList(prev =>
      prev.map(s => s.id === id ? { ...s, enabled: !s.enabled } : s)
    );
    const schedule = scheduleList.find(s => s.id === id);
    toast({
      title: schedule?.enabled ? "Schedule Disabled" : "Schedule Enabled",
      description: `${schedule?.name} has been ${schedule?.enabled ? "disabled" : "enabled"}`,
    });
  };

  const emailReport = (reportName: string) => {
    toast({
      title: "Email Sent",
      description: `${reportName} has been sent to configured recipients`,
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
          <p className="text-muted-foreground">
            Generate and export facility management reports
          </p>
        </div>
        <div className="flex gap-2">
          <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Select period" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="today">Today</SelectItem>
              <SelectItem value="this-week">This Week</SelectItem>
              <SelectItem value="this-month">This Month</SelectItem>
              <SelectItem value="last-month">Last Month</SelectItem>
              <SelectItem value="this-quarter">This Quarter</SelectItem>
              <SelectItem value="custom">Custom Range</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Stats */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Reports Generated</p>
                <p className="text-2xl font-bold">156</p>
              </div>
              <FileText className="h-8 w-8 text-muted-foreground" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">This Month</p>
                <p className="text-2xl font-bold text-blue-600">23</p>
              </div>
              <Calendar className="h-8 w-8 text-blue-600" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Scheduled</p>
                <p className="text-2xl font-bold text-green-600">{scheduleList.filter(s => s.enabled).length}</p>
              </div>
              <Clock className="h-8 w-8 text-green-600" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Email Sent</p>
                <p className="text-2xl font-bold">89</p>
              </div>
              <Mail className="h-8 w-8 text-muted-foreground" />
            </div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="generate" className="space-y-4">
        <TabsList>
          <TabsTrigger value="generate">Generate Reports</TabsTrigger>
          <TabsTrigger value="scheduled">Scheduled Reports</TabsTrigger>
          <TabsTrigger value="history">Report History</TabsTrigger>
        </TabsList>

        <TabsContent value="generate" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {reportTypes.map((report) => {
              const Icon = report.icon;
              const isPdfGenerating = generatingReport === `${report.id}-pdf`;
              const isExcelGenerating = generatingReport === `${report.id}-excel`;

              return (
                <Card key={report.id} className="hover:shadow-md transition-shadow">
                  <CardHeader>
                    <div className="flex items-start justify-between">
                      <div className="p-2 bg-primary/10 rounded-lg">
                        <Icon className="h-5 w-5 text-primary" />
                      </div>
                      <span className="text-xs text-muted-foreground bg-muted px-2 py-1 rounded">
                        {report.frequency}
                      </span>
                    </div>
                    <CardTitle className="text-lg mt-3">{report.title}</CardTitle>
                    <CardDescription>{report.description}</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        className="flex-1"
                        onClick={() => generatePDF(report.id, report.title)}
                        disabled={!!generatingReport}
                      >
                        {isPdfGenerating ? (
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <FileText className="mr-2 h-4 w-4" />
                        )}
                        PDF
                      </Button>
                      <Button
                        variant="outline"
                        className="flex-1"
                        onClick={() => generateExcel(report.id, report.title)}
                        disabled={!!generatingReport}
                      >
                        {isExcelGenerating ? (
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                          <FileSpreadsheet className="mr-2 h-4 w-4" />
                        )}
                        Excel
                      </Button>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="flex-1"
                        onClick={() => previewReport(report)}
                      >
                        <Eye className="mr-2 h-4 w-4" />
                        Preview
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="flex-1"
                        onClick={() => emailReport(report.title)}
                      >
                        <Mail className="mr-2 h-4 w-4" />
                        Email
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </TabsContent>

        <TabsContent value="scheduled">
          <Card>
            <CardHeader>
              <CardTitle>Scheduled Reports</CardTitle>
              <CardDescription>
                Configure automatic report generation and distribution
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {scheduleList.map((schedule) => (
                  <div key={schedule.id} className="flex items-center justify-between p-4 border rounded-lg">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <p className="font-medium">{schedule.name}</p>
                        <Badge variant={schedule.enabled ? "success" : "secondary"}>
                          {schedule.enabled ? "Active" : "Disabled"}
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground mt-1">
                        <Clock className="inline h-3 w-3 mr-1" />
                        {schedule.schedule}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        <Mail className="inline h-3 w-3 mr-1" />
                        {schedule.recipients}
                      </p>
                    </div>
                    <div className="flex items-center gap-3">
                      <Switch
                        checked={schedule.enabled}
                        onCheckedChange={() => toggleSchedule(schedule.id)}
                      />
                      <Button variant="outline" size="sm">
                        Configure
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="history">
          <Card>
            <CardHeader>
              <CardTitle>Report History</CardTitle>
              <CardDescription>
                Previously generated reports
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {reportHistory.map((report) => (
                  <div
                    key={report.id}
                    className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      {report.type === "PDF" ? (
                        <FileText className="h-8 w-8 text-red-500" />
                      ) : (
                        <FileSpreadsheet className="h-8 w-8 text-green-600" />
                      )}
                      <div>
                        <p className="font-medium">{report.name}</p>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <span>Generated on {report.date}</span>
                          <span>•</span>
                          <span>{report.size}</span>
                          <Badge variant="outline" className="text-xs">{report.type}</Badge>
                        </div>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="ghost" size="sm" onClick={() => {
                        toast({ title: "Preview", description: "Opening preview..." });
                      }}>
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => downloadHistoryReport(report)}>
                        <Download className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => emailReport(report.name)}>
                        <Mail className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Preview Dialog */}
      <Dialog open={previewDialog.open} onOpenChange={(open) => setPreviewDialog({ open, report: null })}>
        <DialogContent className="sm:max-w-[700px]">
          <DialogHeader>
            <DialogTitle>{previewDialog.report?.title} Preview</DialogTitle>
            <DialogDescription>
              Preview for {selectedPeriod.replace("-", " ")}
            </DialogDescription>
          </DialogHeader>
          <div className="border rounded-lg p-6 bg-muted/30 space-y-4">
            <div className="text-center border-b pb-4">
              <h2 className="text-xl font-bold">SOFT SERVICES ERP</h2>
              <p className="text-lg">{previewDialog.report?.title}</p>
              <p className="text-sm text-muted-foreground">Generated: {new Date().toLocaleDateString()}</p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="p-3 border rounded">
                <p className="text-sm text-muted-foreground">Tasks Completed</p>
                <p className="text-2xl font-bold">156</p>
              </div>
              <div className="p-3 border rounded">
                <p className="text-sm text-muted-foreground">Attendance Rate</p>
                <p className="text-2xl font-bold">94.5%</p>
              </div>
              <div className="p-3 border rounded">
                <p className="text-sm text-muted-foreground">Inspection Score</p>
                <p className="text-2xl font-bold">87%</p>
              </div>
              <div className="p-3 border rounded">
                <p className="text-sm text-muted-foreground">SLA Compliance</p>
                <p className="text-2xl font-bold">92%</p>
              </div>
            </div>

            <p className="text-sm text-muted-foreground text-center">
              This is a preview. Generate PDF or Excel for full report.
            </p>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPreviewDialog({ open: false, report: null })}>
              Close
            </Button>
            <Button onClick={() => {
              if (previewDialog.report) {
                generatePDF(previewDialog.report.id, previewDialog.report.title);
                setPreviewDialog({ open: false, report: null });
              }
            }}>
              <Download className="mr-2 h-4 w-4" />
              Download PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
